// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeEt23PovUXgR0ya7HsihP9kMXRi2Yue8',
    appId: '1:674387186130:web:9081394be8f40b2bea780b',
    messagingSenderId: '674387186130',
    projectId: 'sheeta-noras',
    authDomain: 'sheeta-noras.firebaseapp.com',
    storageBucket: 'sheeta-noras.appspot.com',
    measurementId: 'G-7LDM4GSHH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5ZqI6ikQuIq4tNoD13h9mWoxYWSrexOs',
    appId: '1:674387186130:android:47b845cd3ef495eaea780b',
    messagingSenderId: '674387186130',
    projectId: 'sheeta-noras',
    storageBucket: 'sheeta-noras.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy6gLClqjCzjQDu-FDFnnKwZ11moVBci8',
    appId: '1:674387186130:ios:41a921bc6519e19eea780b',
    messagingSenderId: '674387186130',
    projectId: 'sheeta-noras',
    storageBucket: 'sheeta-noras.appspot.com',
    iosBundleId: 'com.example.sheeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy6gLClqjCzjQDu-FDFnnKwZ11moVBci8',
    appId: '1:674387186130:ios:d561bb8346d11936ea780b',
    messagingSenderId: '674387186130',
    projectId: 'sheeta-noras',
    storageBucket: 'sheeta-noras.appspot.com',
    iosBundleId: 'com.example.sheeta.RunnerTests',
  );
}
